export const searchProfileInitialValues = {
  nickname: "",
  firstName: "",
  middleName: "",
  lastName: "",
  secondLastName: "",
  documentType: "",
  documentNumber: "",
  birthDate: "",
  departmentOfBirth: "",
  cityOfBirth: "",
  mobilePhone: "",
  sex: "",
  eyeColor: "",
  skinColor: "",
  hairType: "",
  hairColor: "",
  height: "",
  departmentOfLastSighting: "",
  cityOfLastSighting: "",
  imgUrl: "",
  "input-upload-img": "",
};
export const filtersInitialValues = {
  firstName: "",
  middleName: "",
  lastName: "",
  secondLastName: "",
  documentType: "",
  documentNumber: "",
  birthDate: "",
  departmentOfLastSighting: "",
  cityOfLastSighting: "",
  mobilePhone: "",
  sex: "",
  eyeColor: "",
  skinColor: "",
  hairType: "",
  hairColor: "",
  height: "",
};
export const personInitialValues = {
  nickname: "",
  firstName: "",
  middleName: "",
  lastName: "",
  secondLastName: "",
  documentType: "",
  documentNumber: "",
  birthDate: "",
  departmentOfLastSighting: "",
  cityOfLastSighting: "",
  mobilePhone: "",
  sex: "",
  eyeColor: "",
  skinColor: "",
  hairType: "",
  hairColor: "",
  height: "",
  imgUrl: "",
  "input-upload-img": "",
  contactEmail: "",
};
