export const missingPersonInitialValues = {
  firstName: "",
  middleName: "",
  lastName: "",
  secondLastName: "",
  documentType: "",
  documentNumber: "",
  birthDate: "",
  departmentOfBirth: "",
  cityOfBirth: "",
  mobilePhone: "",
  gender: "",
  eyeColor: "",
  skinColor: "",
  hairType: "",
  hairColor: "",
  height: "",
  departmentOfLastSighting: "",
  cityOfLastSighting: "",
  imgUrl: "",
};
